version: '3'
services:
  dynamodb-local:
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-local:/home/dynamodblocal

volumes:
  dynamodb-local:
